### ISSUE TITLE
can you add timeout,renderDelay options 

### ISSUE THREAD

**Issue by ethicalbughunter** [Tazeg/webshot#4]
Thanks for sharing your tool.

sometimes some websites are not captured due to this issue i belief.

**Comment by Tazeg** [comment]
Fixed in https://github.com/Tazeg/webshot/commit/a93f44dafe70fb2c39b4adf8852579d85fc1fbd1
Please try v1.0.1 : https://github.com/Tazeg/webshot/releases/tag/v1.0.1

**Comment by ethicalbughunter** [comment]
Thank you for the update, currently i am facing issue when i use this command  " npm start " i install through git clone method.

previous version is still working for me.

error

```
npm run start


> webshot@1.0.1 start /home/pc/webshot
> electron .

[2503:0601/184738.976366:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/pc/webshot/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
```
when i run using root(sudo) again it gives me error 

```
sudo npm run start
[sudo] password for pc: 

> webshot@1.0.1 start /home/pc/webshot
> electron .

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webshot@1.0.1 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webshot@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-01T13_18_06_793Z-debug.log

```

**Comment by Tazeg** [comment]
you should not install with sudo. Try this : 
```
sudo rm -rf node_modules/
sudo rm package-lock.json
sudo chown -R user:user .
npm install
```
(change `user` with your linux user name).

**Comment by ethicalbughunter** [comment]
thank you for the quick update,still facing the same issue after following your steps, i also install from scratch but no luck.

just for confirmation i used ```sudo chown -R pc:pc .```
pc is my linux username.


Error 
```
npm run start

> webshot@1.0.1 start /home/pc/webshot
> electron .

[4675:0601/200001.583940:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/pc/webshot/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.

```
PS:

i am reproducing this in Arch Linux ,chromium browser.previous webshot version is perfectly working

**Comment by ethicalbughunter** [comment]
issue is fixed 

by firing this command  

```

sudo chown root chrome-sandbox
chmod 4755 chrome-sandbox

```
can you please add an timeout option button and thread option,because sometimes it skip some websites and render a blackscreen and whitescreen image(Screenshot) 

Thank you

**Comment by Tazeg** [comment]
Yes it's an Electron issue : https://github.com/electron/electron/issues/17972

Ok i will think about a timeout option and thread.
